import { ConvexClient } from "convex/browser";
import "./globals.css";
import Provider from "./provider";
import { ConvexProvider } from "convex/react";

export const metadata = {
  title: "Jay Prajapati, Bolt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ConvexProvider>
          <Provider>{children}</Provider>
        </ConvexProvider>
      </body>
    </html>
  );
}
