import "./globals.css";
import Provider from "./provider";

export const metadata = {
  title: "Jay Prajapati, Bolt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
